# Generated by Django 3.1.14 on 2022-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0004_listmodel_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('listobject', models.ManyToManyField(to='ToDoList.ListModel')),
            ],
        ),
    ]
