# Generated by Django 3.1.14 on 2022-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='listobject',
        ),
        migrations.AddField(
            model_name='listmodel',
            name='Tag',
            field=models.ManyToManyField(to='ToDoList.Tags'),
        ),
    ]
