# Generated by Django 3.1.14 on 2022-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0006_auto_20220218_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='name',
        ),
        migrations.AddField(
            model_name='tags',
            name='Title',
            field=models.CharField(default='Tags', max_length=50),
            preserve_default=False,
        ),
    ]
