# Generated by Django 3.1.14 on 2022-02-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0007_auto_20220218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
