# Generated by Django 3.1.14 on 2022-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0008_auto_20220218_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
