# Generated by Django 3.1.14 on 2022-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0009_auto_20220219_0359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='Description',
            field=models.CharField(editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='Tag',
            field=models.ManyToManyField(blank=True, to='ToDoList.Tags'),
        ),
    ]
